name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Good ideas make the project better.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does your suggestion solve, or what is the motivation behind it?
      placeholder: When I use ..., I find that ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or improvement you'd like to see.
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Are there similar products or features you've seen? Please share links.
      placeholder: "e.g. https://example.com/feature"

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references.
